# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1if3Z4phxIMpDe3I7vjYg0M1Ch-jC1DQZ
"""

print ("hello")